name: Build
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/light-ai-tool

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    permissions:
      contents: write
      id-token: write

    if: ${{ github.actor }} != "GitHub Action"
    steps:
    - uses: actions/checkout@v4
    - uses: PyO3/maturin-action@v1.43.0
      with:
        args: --release
        
    - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: bloodnight
        repository-url: https://test.pypi.org/legacy/
        packages-dir: wheels/